param(
    [int]$Repetitions = 0,
    [switch]$Clean,
    [string]$ConfigDir = "experiments/configs"
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$RunExperimentScript = Join-Path $ScriptDir "Run-Experiment.ps1"
$NotebooksDir = Join-Path $RepoRoot "notebooks"
$NotebookPath = Join-Path $NotebooksDir "analisis_rendimiento.ipynb"

Push-Location $RepoRoot

Write-Host "=== Running All Experiments ===" -ForegroundColor Cyan
Write-Host ""

if ($Clean) {
    Write-Host "Cleaning previous experiment folders..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue results/experiments/* 2>$null
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue results/raw/* 2>$null
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue results/meta/* 2>$null
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue results/processed/* 2>$null
    Write-Host "Cleaned." -ForegroundColor Green
}

$configFiles = Get-ChildItem -Path $ConfigDir -Filter "*.json" -File -ErrorAction SilentlyContinue
if (-not $configFiles) {
    Write-Error "No config files found in $ConfigDir"
    Pop-Location
    exit 1
}

Write-Host "Found $($configFiles.Count) config(s) in $ConfigDir" -ForegroundColor Green
Write-Host ""

foreach ($cfg in $configFiles) {
    $cfgPath = $cfg.FullName
    $relPath = Resolve-Path -Relative $cfgPath
    Write-Host "Running: $relPath" -ForegroundColor Cyan
    
    try {
        & $RunExperimentScript -ConfigPath $cfgPath
        Write-Host "Completed: $relPath" -ForegroundColor Green
    } catch {
        Write-Warning "Failed to run $relPath : $_"
    }
    Write-Host ""
}

Write-Host "=== All Experiments Completed ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Para analizar los resultados:" -ForegroundColor Yellow
Write-Host "   1. Abre el notebook: notebooks/analisis_rendimiento.ipynb" -ForegroundColor White
Write-Host "   2. Ejecuta todas las celdas (Run All)" -ForegroundColor White
Write-Host "   3. Los resultados procesados se guardaran en: results/processed/" -ForegroundColor White
Write-Host ""
Write-Host "El notebook incluye:" -ForegroundColor Cyan
Write-Host "   - Estadisticas descriptivas" -ForegroundColor White
Write-Host "   - Analisis comparativo entre modos" -ForegroundColor White
Write-Host "   - Calculo de speedup y eficiencia" -ForegroundColor White
Write-Host "   - Tests estadisticos (ANOVA, Kruskal-Wallis, Mann-Whitney)" -ForegroundColor White
Write-Host "   - Visualizaciones interactivas" -ForegroundColor White
Write-Host "   - Exportacion de graficas y reportes" -ForegroundColor White
Write-Host ""

Write-Host "Generating experiment metadata report..." -ForegroundColor Cyan

$cpu = Get-CimInstance -ClassName Win32_Processor | Select-Object -First 1
$mem = Get-CimInstance -ClassName Win32_ComputerSystem
$os = Get-CimInstance -ClassName Win32_OperatingSystem

$reportPath = "results/EXPERIMENT_INFO.md"
$currentDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$totalMemGB = [math]::Round($mem.TotalPhysicalMemory / 1GB, 2)
$reportContent = @"
# Proof-of-Work Miner: Experiment Metadata
**Date:** $currentDate

## System Information
- **PC Name:** $($env:COMPUTERNAME)
- **User:** $($env:USERNAME)
- **CPU:** $($cpu.Name)
- **CPU Cores:** $($cpu.NumberOfCores)
- **Logical Processors:** $($cpu.NumberOfLogicalProcessors)
- **Total Memory:** $totalMemGB GB
- **Operating System:** $($os.Caption) $($os.Version)

## Experiment Configuration
All experiments were executed using configurations from experiments/configs/:
- **Modes tested:** Sequential, Concurrent (with CPU pinning), Parallel
- **Threads:** 1, 2, 4 (varies by mode)
- **Difficulty:** 20 bits (low), 22 bits (medium)
- **Repetitions per config:** 5
- **Timeout:** 120-180 seconds
- **Seed:** 42

## Data Location
- **Raw results:** results/raw/*.csv
- **Metadata:** results/meta/*.meta.json
- **Analysis notebook:** notebooks/analisis_rendimiento.ipynb

## Next Steps
1. Open notebooks/analisis_rendimiento.ipynb in Jupyter/VS Code
2. Execute all cells to generate:
   - Processed summary (results/processed/summary.csv)
   - Statistical analysis (results/processed/statistical_summary.txt)
   - Configuration stats (results/processed/config_stats.csv)
   - Plots (results/processed/plots/*.png)

---
*Generated by run_all_modes.ps1*
"@


$reportContent | Out-File -Encoding UTF8 $reportPath
Write-Host "Experiment metadata written to: $reportPath" -ForegroundColor Green
Write-Host ""
Write-Host "Experimentos completados!" -ForegroundColor Green
Write-Host "   Abre el notebook para analizar los resultados." -ForegroundColor White

Pop-Location
